### ISSUE TITLE
Parameter with an array is not being validated and maybe not parsed correctly

### ISSUE THREAD

**Issue by jamidon** [mikestead/swagger-routes#11]
I'm trying to track down a problem with passing arrays to some of my POST methods where validation isn't happening. I've attached part of a Swagger 2.0 schema JSON file: [api.txt](https://github.com/mikestead/swagger-routes/files/731389/api.txt) that illustrates the problem. I did verify that it is valid by checking it against [Swagger 2.0 Parser](http://bigstickcarpet.com/swagger-parser/www/index.html).

The swagger-ui looks like this:
![swagger-ui](https://cloud.githubusercontent.com/assets/3597350/22317250/739cbc7c-e340-11e6-8e4d-60d9e22c006e.png)

As you can see, the page doesn't seem to know an array of values can be sent to the organizations/add interface. Also, if I pass something invalid like:

   `{ "name": "foo", "abbreviation": "bar" }`

which is not an array or

   `[ { "name21": "foo", "abbreviation": "bar" } ]`

where `name21` is invalid.

My little bootstrap for hosting this is:
```javascript
const swaggerRoutes = require('swagger-routes');
const restify = require('restify');

const server = restify.createServer();
server.use(restify.acceptParser(server.acceptable));
server.use(restify.authorizationParser());
server.use(restify.dateParser());
server.use(restify.queryParser({ mapParams: false }));
server.use(restify.jsonp());
server.use(restify.gzipResponse());
server.use(restify.bodyParser());
server.use(restify.CORS());
server.use(restify.fullResponse());

function createHandler(operation) {
  return function handler(req, res, next) {
    res.send(operation.id);
  };
}

swaggerRoutes(server, {
  api: './api.json',
  handlers: createHandler
});
server.listen(8080);
```
Any idea as to where to look to track this down?

Thanks.

**Comment by jamidon** [comment]
I've traced it down into swaggerSpec.js in the createParamGroupSchemas() method. This method assumes each parameter's schema has the 'properties' property whereas the schema for an array parameter doesn't.

I'm wondering if I were possible to flatten out the array definitions to remove the $ref's if the jsonschema validate method would work.

Thoughts?

**Comment by mikestead** [comment]
Thanks for the details. I'm on a short break right now but will take a look next week when I'm back.

**Comment by jamidon** [comment]
Thanks.

-- jda

**Comment by jamidon** [comment]
I found a way around this issue, and I'm fairly certain it has nothing to do with swagger-routes but the jsonschema module. 

If I change the definition of the parameter in the add method from:
```javascript
        "parameters": [
          {
            "name": "organization",
            "in": "body",
            "description": "organization(s) to add to the system",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewOrganizations"
            }
          }
        ]
````
to
```javascript
        "parameters": [
          {
            "name": "organization",
            "in": "body",
            "description": "organization(s) to add to the system",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/NewOrganization"
              }
            }
          }
        ],
```
everything works as expected. Essentially the difference in the two definitions is the second one is a bit more explicit but otherwise seems equivalent to me.

Anyway, sorry for the noise.

**Comment by mikestead** [comment]
Good to hear, thanks for posting the solution 👍
